import { utils, writeFile } from 'xlsx';
import { Income, Expense, Budget } from './db';

interface ExcelReportData {
  incomes: Income[];
  expenses: Expense[];
  budgets: Budget[];
  selectedMonth: string;
  username: string;
}

// Helper to format date to YYYY-MM-DD
const formatDate = (dateStr: string) => {
  return dateStr; // Already in YYYY-MM-DD format from DB
};

// Helper to format currency
const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export function generateExcelReport(data: ExcelReportData) {
  const { incomes, expenses, budgets, selectedMonth, username } = data;

  // Filter data based on selected month
  const filteredIncomes = selectedMonth === 'all'
    ? incomes
    : incomes.filter(i => i.bulan === selectedMonth);

  const filteredExpenses = selectedMonth === 'all'
    ? expenses
    : expenses.filter(e => e.bulan === selectedMonth);

  const filteredBudgets = selectedMonth === 'all'
    ? budgets
    : budgets.filter(b => b.bulan === selectedMonth);

  // Calculate totals
  const totalIncome = filteredIncomes.reduce((sum, i) => sum + i.jumlah, 0);
  const totalExpense = filteredExpenses.reduce((sum, e) => sum + e.jumlah, 0);
  const netBalance = totalIncome - totalExpense;

  // Create workbook
  const wb = utils.book_new();

  // Summary Sheet
  const summaryData = [
    ['FINANCIAL REPORT', '', ''],
    ['Period', selectedMonth === 'all' ? 'All Periods' : selectedMonth, ''],
    ['Generated by', username, ''],
    ['Generated on', new Date().toLocaleDateString('en-US'), ''],
    ['', '', ''],
    ['SUMMARY', '', ''],
    ['Total Income', formatCurrency(totalIncome), `=SUM('Income'!F:F)`],
    ['Total Expenses', formatCurrency(totalExpense), `=SUM('Expenses'!F:F)`],
    ['Net Balance', formatCurrency(netBalance), ''],
    ['', '', ''],
    ['Budget Performance', '', ''],
  ];

  // Add budget summary rows
  filteredBudgets.forEach(b => {
    const realized = filteredExpenses
      .filter(e => e.kategori === b.kategori)
      .reduce((sum, e) => sum + e.jumlah, 0);
    const variance = b.anggaran - realized;
    const status = realized <= b.anggaran ? 'On Track' : 'Over Budget';
    summaryData.push([b.kategori, formatCurrency(b.anggaran), formatCurrency(realized), formatCurrency(variance), status]);
  });

  const summarySheet = utils.aoa_to_sheet(summaryData);
  utils.book_append_sheet(wb, summarySheet, 'Summary');

  // Income Sheet
  const incomeRows = [['Date', 'Source', 'Category', 'Method', 'Amount']];
  filteredIncomes.forEach(i => {
    incomeRows.push([formatDate(i.tanggal), i.sumber, i.kategori, i.metode, i.jumlah]);
  });
  // Add total row
  incomeRows.push(['', '', '', 'TOTAL', filteredIncomes.reduce((sum, i) => sum + i.jumlah, 0)]);

  const incomeSheet = utils.aoa_to_sheet(incomeRows);
  // Set column widths (approx)
  incomeSheet['!cols'] = [
    { wch: 12 }, // Date
    { wch: 20 }, // Source
    { wch: 15 }, // Category
    { wch: 15 }, // Method
    { wch: 15 }, // Amount
  ];
  utils.book_append_sheet(wb, incomeSheet, 'Income');

  // Expenses Sheet
  const expenseRows = [['Date', 'Name', 'Category', 'Method', 'Amount']];
  filteredExpenses.forEach(e => {
    expenseRows.push([formatDate(e.tanggal), e.nama, e.kategori, e.metode, e.jumlah]);
  });
  // Add total row
  expenseRows.push(['', '', '', 'TOTAL', filteredExpenses.reduce((sum, e) => sum + e.jumlah, 0)]);

  const expenseSheet = utils.aoa_to_sheet(expenseRows);
  expenseSheet['!cols'] = [
    { wch: 12 },
    { wch: 25 },
    { wch: 15 },
    { wch: 15 },
    { wch: 15 },
  ];
  utils.book_append_sheet(wb, expenseSheet, 'Expenses');

  // Budget Sheet
  const budgetRows = [['Category', 'Budget', 'Actual', 'Variance', 'Status']];
  filteredBudgets.forEach(b => {
    const realized = filteredExpenses
      .filter(e => e.kategori === b.kategori)
      .reduce((sum, e) => sum + e.jumlah, 0);
    const variance = b.anggaran - realized;
    const status = realized <= b.anggaran ? 'On Track' : 'Over Budget';
    budgetRows.push([b.kategori, b.anggaran, realized, variance, status]);
  });

  const budgetSheet = utils.aoa_to_sheet(budgetRows);
  budgetSheet['!cols'] = [
    { wch: 20 },
    { wch: 15 },
    { wch: 15 },
    { wch: 15 },
    { wch: 12 },
  ];
  utils.book_append_sheet(wb, budgetSheet, 'Budget');

  // Category Breakdown (Expenses by Category)
  const categoryTotals: { [key: string]: number } = {};
  filteredExpenses.forEach(e => {
    if (!categoryTotals[e.kategori]) categoryTotals[e.kategori] = 0;
    categoryTotals[e.kategori] += e.jumlah;
  });

  const categoryRows = [['Category', 'Amount', '% of Total']];
  Object.entries(categoryTotals)
    .sort((a, b) => b[1] - a[1])
    .forEach(([category, amount]) => {
      const percent = totalExpense > 0 ? ((amount / totalExpense) * 100).toFixed(1) + '%' : '0%';
      categoryRows.push([category, amount, percent]);
    });
  // Total row
  categoryRows.push(['TOTAL', totalExpense, '100%']);

  const categorySheet = utils.aoa_to_sheet(categoryRows);
  categorySheet['!cols'] = [
    { wch: 20 },
    { wch: 15 },
    { wch: 12 },
  ];
  utils.book_append_sheet(wb, categorySheet, 'Category Breakdown');

  // Generate filename
  const periodStr = selectedMonth === 'all' ? 'all-periods' : selectedMonth;
  const fileName = `financial-report-${periodStr}-${new Date().toISOString().split('T')[0]}.xlsx`;

  // Save file
  writeFile(wb, fileName);
}
